### ISSUE TITLE
FusionGen does not send mail

### ISSUE THREAD

**Issue by Tony931023** [FusionGen/FusionGEN#126]
when registering new users and using email validation, the email never reaches its recipient

**Comment by Err0r1** [comment]
You need a working mailserver or you have to use an external mailserver.

**Comment by Tony931023** [comment]
I will mount a local mail server and try, gmail validates the account but the mail does not arrive

**Comment by Slipy007** [comment]
> I will mount a local mail server and try, gmail validates the account but the mail does not arrive

Gmail doesn't like new domains if that is what your using. There are a lot of steps in order for gmail to consider your domain email being safe by sending email through your domain email program. 

So I'd suggest if you or anyone using email verify and have fusion gen on your own domain to work on that before enabling email verify because they will never get the email. It will look like this if trying to send and email to someone with there email as gmail. Now I'm not saying I know anything but this is what i found out.

You will get this bounce back if you try to email using your email domain program and trying to send to someones gmail:

It took me a few hours to fix STMP and add all this extra crap just so gmail sees my domain email as safe if I'm sending through my email program domain.

`<sendersemailaddress@gmail.com>: host gmail-smtp-in.l.google.com[IP]
    said: 550-5.7.1 [mylinixserverIP      12] Our system has detected that this
    message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam
    sent to Gmail, 550-5.7.1 this message has been blocked. Please visit
    550-5.7.1  https://support.google.com/mail/?p=UnsolicitedMessageError 550
    5.7.1  for more information.
    craploadofnumbers.534 - gsmtp (in reply to
    end of DATA command)`

Now if I'm totally wrong someone please let me know so I can fix it.

**Comment by Err0r1** [comment]
You need DKIM/SPF/MX/DMARC records

**Comment by Slipy007** [comment]
> You need DKIM/SPF/MX/DMARC records

Yes I've done all of that now. But I think I'm waiting on them to verify it all. I uploaded my DNS TXT record to them and it got approved but everything is waiting to be seen like the CNAME etc.

**Comment by Slipy007** [comment]
Ok I fixed a few things and now it send to gmail with no bounce back. But I don't get the email on my gmail account. Know what I'm doing wrong?

**Comment by mpfans** [comment]
Fusiongen can't send the registration email, and then the password recovery page can't be opened. These two bugs have not been fixed.

**Comment by Err0r1** [comment]
FusionGen has nothing todo with mailserver
PW recovery is broken atm, but fixed in the update

**Comment by Slipy007** [comment]
> FusionGen has nothing todo with mailserver PW recovery is broken atm, but fixed in the update

I was talking about my linux host from post above.

**Comment by mpfans** [comment]
> 

The latest version also has the above two bugs

**Comment by Err0r1** [comment]
> > 
> 
> The latest version also has the above two bugs

Yes, is known, will be fixed with the update

**Comment by mpfans** [comment]
Temporary solution: restore to the branch before merging srp6, and everything works.
