### ISSUE TITLE
Register, XSS prevention.

### ISSUE THREAD

**Issue by lastdarken** [FusionGen/FusionGen#26]
Hi 
First of all, i can't creat a pull not in my rank.

I shared bug + Fix for register, XSS prevention.

I,think this is for register page modules;
and
I,see in the logs; buger want update table "account", but this rank closed for $user and rejected to my php select secure ranks;

<Details>
ERROR - 2020-05-10 10:15:20 --> Query error: UPDATE command denied to user 'usersite'@'cp.ovh6.com' for table 'account'
</Details>

----

This not testing but for fix Try:

$this->plugins->{$this->config->item->template->format('forum_bridge')}->register($data['username'], $data['password'], $data['email']), false, false, true, false);
&
$this->plugins->{$this->config->item->template->format('forum_bridge')}->register($data['username'], $data['password'], $data['email']), false, false, true, false);

GL.

**Comment by alexandre433** [comment]
Hello,
I'm confused why are you posting that code?
And if you want to implement code in the issue you can use this character ` before and after a code it will display like this `example code`

The error thrown into the logs means that the user given to the website doesn't have permission to update in the database.

And that code, from what I'm looking at, doesn't fix anything. Because there is no context, you don't say what file that should go on, nor what are you trying to actually fix, besides what is said on the title.

Another thing, you CAN create pull requests, you just need to fork, change on the forked repository and then pull request on this repository of the forked and changed repository for any questions you can follow this tutorial provided by github - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by lastdarken** [comment]
Is wrong...

Regiser ! user ! update table:D?
Bug used exploit to in register/page and want "update" tabels...
Don't you understand?!?

No matter, I solved the problem.
but i shered bug for project.

B

**Comment by alexandre433** [comment]
Sorry I don't understand what you're saying..

This does not fix anything, currently we don't have a forum bridge that works, thus what you wrote is unusable.

**Comment by lastdarken** [comment]
ican't shered full fixed bug;

I just gave an example;

You don't care about security at all...

**Comment by alexandre433** [comment]
I do, but this is not proper english that, at least, I cannot understand,

> Regiser ! user ! update table:D?

wth is that?
This does not explain, what it fixes properly, HOW does this fix XSS?

**Comment by alexandre433** [comment]
And where? on the Register page? or Login? Shoutbox (yes it was removed)? Connection to x table or database?

**Comment by lastdarken** [comment]
This is a exploit for register page....
and buger used for upgrade tables "....."


:)

**Comment by alexandre433** [comment]
This is a exploit or this fixes an exploit?

**Comment by alexandre433** [comment]
Follow this issue as a template to create a proper issue please - https://github.com/FusionGen/FusionGen/issues/2

**Comment by lastdarken** [comment]
The site injects into the database:|
buger want by register/page update table:
Query insert: UPDATE command to user 'usersite'@'cp.ovh6.com' for table 'account'

**Comment by alexandre433** [comment]
In order to make this process simplified for you and us, we'd love if you followed this simple yet informative format.

- What are you specifically reporting (one report per issue):
- How do we replicate this issue that you are encountering?`:
- Are you hosting FusionGen on a All-in-One Package or an Webhost:
- Have you made any personal modifications? If so, What?:
- PHP Version:

After following the format, Please wait for a reply. There's no need to bump or ping us about this. We'll get to it when we get to it!

Thank you for reporting found issues. And thank you for showing us continous support!

**Comment by lastdarken** [comment]
Please read my full posts from the beginning ... for now


I'm not bored right now.
