### ISSUE TITLE
Fusion CMS STORE

### ISSUE THREAD

**Issue by MttAI-dev** [FusionGen/FusionGEN#40]
i have installed fusionGen master and there got some errors on realms its not working correct it says that realms not working but shows players online and realm characters. also do not working web store, impossible to buy any item. when clicking on item its not adding in to cart and does nothing, no error, no redirects nothing there is realms error:

`A PHP Error was encountered
Severity: Warning
Message: count(): Parameter must be an array or an object that implements Countable
Filename: libraries/realms.php
Line Number: 201
100%">`
If need link where that error is mttwow.sytes.net u can find it here.

**Comment by OMGhixD-OG** [comment]
Please use either the Console or Query option instead of the item option.

The item option is very old and out of date. It is so old that we are considering to put it into the deprecated function archive.

Item Mailing can and should be done through console commands. 
Example "send items {CHARACTER} "Title" "Description" ITEMID1:QUANTITY ITEMID2:QUANTITY ITEMID3:QUANTITY"
