### ISSUE TITLE
SOAP can't send items

### ISSUE THREAD

**Issue by veselin-ugrinov** [FusionGen/FusionGEN#52]
When i use SOAP as a way to distribute items from the vote points shop, i allways get this error :
"Error:
Syntax: .send items #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN] Send a mail to a player. Subject and mail text must be in "". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12."

My stats:
MySQL Version:5.6.28
PHP Version: 7.4.13
Webhost or Xampp(ETC): Xampp 3.2.4
Latest FGEN Version (Yes/No): Yes
Which branch (Master / SRP6): SRP6

**Comment by OMGhixD-OG** [comment]
PHP Version: 7.4.13

![Screenshot_1](https://user-images.githubusercontent.com/3145839/109178519-39454d00-7789-11eb-9c03-32fa03d688a2.png)

**Comment by veselin-ugrinov** [comment]
You are telling me that i cant run it on a newer version ?! o.0

**Comment by DuelistRag3** [comment]
Yes he do

**Comment by newrage** [comment]
send item {CHARACTER} "subject" "text" itemid:count

**Comment by veselin-ugrinov** [comment]
> send item {CHARACTER} "subject" "text" itemid:count

Sry for the stupid question, but where is the file who cointains those lines that i should edit ?

**Comment by OMGhixD-OG** [comment]
This is done through the ACP -> Store Items -> New Item -> Console Command (The old Item) option shouldn't be used as it is extremely old and most likely will be removed.

**Comment by Blacky244-dev** [comment]
Can you explain to me how I adjust this because the way you explain it there per acp - store items -> new item -> console command it doesn't work for me how do I add this then

**Comment by OMGhixD-OG** [comment]
When using Console Command through the webstore. You never want to include the "DOT [.]" as the Console never requires this. so typing exactly as is "send item {CHARACTER} "subject" "text" itemid:count" is the way to do it. I can see you've added a dot, and that is most likely the reason why it is not working.

On the other hand to EDIT the added option/item/product. Simply click the edit icon when entering the "acp -> store item"

And there is also no file to edit the store items. These are submitted per the ACP (Admin Control Panel) or the DB and not per some php or html file.

Since all of the questions above have been properly answered. I'll go ahead and close this.
